Scale line width when rasterizing paths
lafriks/go-svg pull request #9
Opened 2024-12-09 20:25 UTC by pekim

This is an svg rendered using with the rasterx renderer, before the change.
![before](https://github.com/user-attachments/assets/e67ea869-fcee-4af4-b347-6b82aefe6580)

And this is the result after the change.
![after](https://github.com/user-attachments/assets/7f70a2fc-2b98-44c8-954e-1f5b171fada4)

I don't particularly like the way that I'm using mean of the x and y scaling for a scaling factor, but I'm not sure what a better approach would be. From a bit of experimentation browsers appear to be able to scale stroke width for x and y independently. That is horizontal sections of a path have a width that has y scaling applied, and vertical sections have a width with x scaling applied.

I don't believe that any of the supported renderers have any support for drawing strokes with independent x and y thickness scaling. Hence my simplistic approach.  I'm open to suggestions if there's a better way. In any case I think that this is an improvement on the current rendering.

fixes #8

2025-01-14 14:25 UTC, lafriks requested changes
This is not very easy to get it right as scale should apply differently on vertical/horizontal lines (matrix A and D respectively) but that would be quite hard to implement, so at least this should be moved to matrix helper function to keep logic in single place

2025-01-14 14:25 UTC, lafriks commented on renderer/draw2d/draw.go
> +		scale := (m.A + m.D) / 2
I would prefer this calculation to be moved to Matrix2D helper function `LineWidthScale` and than use:

```go
gc.SetLineWidth(svgp.Style.LineWidth * m.LineWidthScale())
```

2025-01-15 07:07 UTC, pekim commented on renderer/draw2d/draw.go
> +		scale := (m.A + m.D) / 2
That makes sense, done.

2025-01-15 08:49 UTC, lafriks approved these changes

2025-01-15 08:50 UTC, merged

2025-01-15 08:52 UTC, lafriks commented
Thanks for PR, released in version v0.5.1